version: '3.1'
services:
  db:
    container_name: db
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: theoguessr
    volumes:
       - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    volumes:
       - .:/theoguessr
    ports: 
       - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_USERNAME: ${MYSQL_USERNAME}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_PROTOCOL: tcp
      DATABASE_CONTAINER_NAME: db
      DATABASE_NAME: theoguessr

volumes:
  dbdata:
